Repository micronaut-projects/micronaut-kubernetes, pull requests merged in 2020-12, with the labels that each got.

#219 [kubernetes] Update common files for branch master
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
Labels: relates-to: build

#142 Add podLabel filtering for Helm support
  examples/micronaut-client/src/test/groovy/micronaut/client/HelloControllerSpec.groovy
  examples/micronaut-service/src/main/resources/bootstrap.yml
  kubernetes-discovery-client/build.gradle
  kubernetes-discovery-client/src/main/java/io/micronaut/kubernetes/client/v1/KubernetesConfiguration.java
  kubernetes-discovery-client/src/main/java/io/micronaut/kubernetes/configuration/KubernetesConfigMapWatcher.java
  kubernetes-discovery-client/src/main/java/io/micronaut/kubernetes/configuration/KubernetesConfigurationClient.java
  kubernetes-discovery-client/src/main/java/io/micronaut/kubernetes/util/KubernetesUtils.java
  kubernetes-discovery-client/src/test/groovy/io/micronaut/kubernetes/configuration/KubernetesConfigurationClientLabelsSpec.groovy
  kubernetes-discovery-client/src/test/resources/k8s/example-service-deployment.yml
  setup-test-namespace.sh
  src/main/docs/guide/config-client.adoc
Labels: type: enhancement

#222 Dependency upgrades
  build.gradle
  kubernetes-discovery-client/build.gradle
Labels: type: dependency-upgrade

#221 [kubernetes] Update common files for branch master
  .github/workflows/gradle.yml
  MAINTAINING.md
Labels: relates-to: build

#224 build: github actions MANTAINING.md
  .github/workflows/release-notes.yml
  MAINTAINING.md
Labels: relates-to: build

#226 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade

#228 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade

#230 [kubernetes] Update common files for branch master
  .github/workflows/gradle.yml
Labels: relates-to: build

#235 [kubernetes] Update common files for branch master
  .github/workflows/dependency-update.yml
Labels: relates-to: build
