Repository micronaut-projects/micronaut-kubernetes, pull requests merged in 2023-05, with the labels that each got.

#564 [kubernetes] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/graalvm.yml
  buildSrc/src/main/groovy/io.micronaut.build.internal.kubernetes-examples.gradle
Labels: relates-to: build

#567 Kubernetes to M5
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.kubernetes-base.gradle
  examples/micronaut-client/build.gradle
  examples/micronaut-client/src/main/java/micronaut/client/HelloController.java
  examples/micronaut-client/src/test/groovy/micronaut/client/HelloControllerSpec.groovy
  examples/micronaut-kubernetes-client/build.gradle
  examples/micronaut-kubernetes-informer/build.gradle
  examples/micronaut-kubernetes-operator/build.gradle
  examples/micronaut-service/build.gradle
  gradle.properties
  gradle/libs.versions.toml
  settings.gradle
Labels: type: dependency-upgrade

#569 Fix for documentation building
  build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.kubernetes-base.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.kubernetes-module.gradle
Labels: relates-to: build, type: docs

#566 [kubernetes] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#576 [kubernetes] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
Labels: relates-to: build
